tmp

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,5 +1,8 @@
 language: go
 
+go:
+  - 1.7
+
 os:
   - linux
   - osx
@@ -25,27 +28,50 @@ before_install:
         fi
         ;;
     *)
+        pushd . ;
+        cd /tmp ;
         curl -sLO https://github.com/kkos/oniguruma/releases/download/v${ONIG_VERSION}/onig-${ONIG_VERSION}.tar.gz ;
         tar xfz onig-${ONIG_VERSION}.tar.gz ;
         cd onig-${ONIG_VERSION} ;
-        ./configure && make && make install ;
+        ./configure && make && sudo make install ;
+        cd $(popd) ;
         ;;
     esac ;
 
 install:
-  - echo "Skipping install phase, because github.com/fstab/grok_exporter has all its dependencies in the vendor/ folder."
+  - |
+    cd .. && mv grok_exporter_onig_test grok_exporter && cd grok_exporter ;
+    case "$MODE" in
+    "STATIC")
+        CGO_LDFLAGS=/usr/local/lib/libonig.a go install . ;
+        if ldd $GOPATH/bin/grok_exporter | grep libonig ;
+        then
+            echo "ERROR: Expected statically linked binary." >&2 ;
+            exit -1 ;
+        fi ;
+        ;;
+    *)
+        go install . ;
+        if ! ldd $GOPATH/bin/grok_exporter | grep libonig ;
+        then
+            echo "ERROR: Expected dynamically linked binary." >&2 ;
+            exit -1 ;
+        fi ;
+        ;;
+    esac ;
 
 script:
-  - go version
   - go test -v $(go list ./... | grep -v /vendor/)
-  - go install .
   - ./integration-test.sh
 
 after_success:
-  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go get golang.org/x/tools/cmd/cover github.com/mattn/goveralls github.com/modocache/gover ; fi
-  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go list ./... | grep -v /vendor/ | while read package ; do go test -covermode count -coverprofile=$(basename $package).coverprofile $package ; done ; fi
-  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gover && goveralls -coverprofile=gover.coverprofile -service=travis-ci ; fi
-  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm *.coverprofile ; fi
-
-go:
-  - tip
+  - |
+    if [[ "$TRAVIS_OS_NAME" == "linux" ]] ;
+    then
+        go get golang.org/x/tools/cmd/cover github.com/mattn/goveralls github.com/modocache/gover ;
+        go list ./... | grep -v /vendor/ | while read package ; do
+            go test -covermode count -coverprofile=$(basename $package).coverprofile $package ;
+            done ;
+        gover && goveralls -coverprofile=gover.coverprofile -service=travis-ci
+        rm *.coverprofile ;
+    fi
